// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbsHz_5AIYKHajT9Zo9gfnU3gy6mxR52M',
    appId: '1:926945286246:web:640d9723667deb334ff5a7',
    messagingSenderId: '926945286246',
    projectId: 'e-shop-flutter-e829f',
    authDomain: 'e-shop-flutter-e829f.firebaseapp.com',
    storageBucket: 'e-shop-flutter-e829f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi1p8SADjsIkcS0bZQF2LB8-8_9XYkFTE',
    appId: '1:926945286246:android:2e75e2f8345331cf4ff5a7',
    messagingSenderId: '926945286246',
    projectId: 'e-shop-flutter-e829f',
    storageBucket: 'e-shop-flutter-e829f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_smBNxe2GFaxn6eADEDr95LfHyc2Yxhk',
    appId: '1:926945286246:ios:faa76e31454095554ff5a7',
    messagingSenderId: '926945286246',
    projectId: 'e-shop-flutter-e829f',
    storageBucket: 'e-shop-flutter-e829f.appspot.com',
    iosBundleId: 'com.example.eShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_smBNxe2GFaxn6eADEDr95LfHyc2Yxhk',
    appId: '1:926945286246:ios:1ff48ca2cc2033d64ff5a7',
    messagingSenderId: '926945286246',
    projectId: 'e-shop-flutter-e829f',
    storageBucket: 'e-shop-flutter-e829f.appspot.com',
    iosBundleId: 'com.example.eShop.RunnerTests',
  );
}
